[package]
name = "okofdb"
version = "0.1.0"
authors = ["Lukas Bergdoll <lukas.bergdoll@gmail.com>"]
description = "One Key One File Database"
license = "Apache-2.0"

[dependencies]
snap = "0.2.4"

[dev-dependencies]
tempdir = "0.3.6"
